/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as DeviceChangeRouteImport } from './routes/device-change'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedLgiRouteImport } from './routes/_authenticated/lgi'
import { Route as AuthenticatedFirmRouteImport } from './routes/_authenticated/firm'
import { Route as AuthenticatedCorpsRouteImport } from './routes/_authenticated/corps'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMediaIndexRouteImport } from './routes/_authenticated/media/index'
import { Route as AuthenticatedLgiIndexRouteImport } from './routes/_authenticated/lgi/index'
import { Route as AuthenticatedFirmIndexRouteImport } from './routes/_authenticated/firm/index'
import { Route as AuthenticatedCorpsIndexRouteImport } from './routes/_authenticated/corps/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedLgiAttendanceRouteImport } from './routes/_authenticated/lgi/attendance'
import { Route as AuthenticatedLgiApprovalsRouteImport } from './routes/_authenticated/lgi/approvals'
import { Route as AuthenticatedFirmJobsRouteImport } from './routes/_authenticated/firm/jobs'
import { Route as AuthenticatedCorpsScanRouteImport } from './routes/_authenticated/corps/scan'
import { Route as AuthenticatedAdminQrRouteImport } from './routes/_authenticated/admin/qr'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceChangeRoute = DeviceChangeRouteImport.update({
  id: '/device-change',
  path: '/device-change',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLgiRoute = AuthenticatedLgiRouteImport.update({
  id: '/lgi',
  path: '/lgi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFirmRoute = AuthenticatedFirmRouteImport.update({
  id: '/firm',
  path: '/firm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCorpsRoute = AuthenticatedCorpsRouteImport.update({
  id: '/corps',
  path: '/corps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMediaIndexRoute = AuthenticatedMediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMediaRoute,
} as any)
const AuthenticatedLgiIndexRoute = AuthenticatedLgiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLgiRoute,
} as any)
const AuthenticatedFirmIndexRoute = AuthenticatedFirmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedFirmRoute,
} as any)
const AuthenticatedCorpsIndexRoute = AuthenticatedCorpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCorpsRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedLgiAttendanceRoute =
  AuthenticatedLgiAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedLgiRoute,
  } as any)
const AuthenticatedLgiApprovalsRoute =
  AuthenticatedLgiApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedLgiRoute,
  } as any)
const AuthenticatedFirmJobsRoute = AuthenticatedFirmJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedFirmRoute,
} as any)
const AuthenticatedCorpsScanRoute = AuthenticatedCorpsScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedCorpsRoute,
} as any)
const AuthenticatedAdminQrRoute = AuthenticatedAdminQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/device-change': typeof DeviceChangeRoute
  '/news': typeof NewsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/corps': typeof AuthenticatedCorpsRouteWithChildren
  '/firm': typeof AuthenticatedFirmRouteWithChildren
  '/lgi': typeof AuthenticatedLgiRouteWithChildren
  '/media': typeof AuthenticatedMediaRouteWithChildren
  '/admin/qr': typeof AuthenticatedAdminQrRoute
  '/corps/scan': typeof AuthenticatedCorpsScanRoute
  '/firm/jobs': typeof AuthenticatedFirmJobsRoute
  '/lgi/approvals': typeof AuthenticatedLgiApprovalsRoute
  '/lgi/attendance': typeof AuthenticatedLgiAttendanceRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/corps/': typeof AuthenticatedCorpsIndexRoute
  '/firm/': typeof AuthenticatedFirmIndexRoute
  '/lgi/': typeof AuthenticatedLgiIndexRoute
  '/media/': typeof AuthenticatedMediaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/device-change': typeof DeviceChangeRoute
  '/news': typeof NewsRoute
  '/admin/qr': typeof AuthenticatedAdminQrRoute
  '/corps/scan': typeof AuthenticatedCorpsScanRoute
  '/firm/jobs': typeof AuthenticatedFirmJobsRoute
  '/lgi/approvals': typeof AuthenticatedLgiApprovalsRoute
  '/lgi/attendance': typeof AuthenticatedLgiAttendanceRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/corps': typeof AuthenticatedCorpsIndexRoute
  '/firm': typeof AuthenticatedFirmIndexRoute
  '/lgi': typeof AuthenticatedLgiIndexRoute
  '/media': typeof AuthenticatedMediaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/device-change': typeof DeviceChangeRoute
  '/news': typeof NewsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/corps': typeof AuthenticatedCorpsRouteWithChildren
  '/_authenticated/firm': typeof AuthenticatedFirmRouteWithChildren
  '/_authenticated/lgi': typeof AuthenticatedLgiRouteWithChildren
  '/_authenticated/media': typeof AuthenticatedMediaRouteWithChildren
  '/_authenticated/admin/qr': typeof AuthenticatedAdminQrRoute
  '/_authenticated/corps/scan': typeof AuthenticatedCorpsScanRoute
  '/_authenticated/firm/jobs': typeof AuthenticatedFirmJobsRoute
  '/_authenticated/lgi/approvals': typeof AuthenticatedLgiApprovalsRoute
  '/_authenticated/lgi/attendance': typeof AuthenticatedLgiAttendanceRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/corps/': typeof AuthenticatedCorpsIndexRoute
  '/_authenticated/firm/': typeof AuthenticatedFirmIndexRoute
  '/_authenticated/lgi/': typeof AuthenticatedLgiIndexRoute
  '/_authenticated/media/': typeof AuthenticatedMediaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/device-change'
    | '/news'
    | '/admin'
    | '/corps'
    | '/firm'
    | '/lgi'
    | '/media'
    | '/admin/qr'
    | '/corps/scan'
    | '/firm/jobs'
    | '/lgi/approvals'
    | '/lgi/attendance'
    | '/admin/'
    | '/corps/'
    | '/firm/'
    | '/lgi/'
    | '/media/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/device-change'
    | '/news'
    | '/admin/qr'
    | '/corps/scan'
    | '/firm/jobs'
    | '/lgi/approvals'
    | '/lgi/attendance'
    | '/admin'
    | '/corps'
    | '/firm'
    | '/lgi'
    | '/media'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/device-change'
    | '/news'
    | '/_authenticated/admin'
    | '/_authenticated/corps'
    | '/_authenticated/firm'
    | '/_authenticated/lgi'
    | '/_authenticated/media'
    | '/_authenticated/admin/qr'
    | '/_authenticated/corps/scan'
    | '/_authenticated/firm/jobs'
    | '/_authenticated/lgi/approvals'
    | '/_authenticated/lgi/attendance'
    | '/_authenticated/admin/'
    | '/_authenticated/corps/'
    | '/_authenticated/firm/'
    | '/_authenticated/lgi/'
    | '/_authenticated/media/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DeviceChangeRoute: typeof DeviceChangeRoute
  NewsRoute: typeof NewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device-change': {
      id: '/device-change'
      path: '/device-change'
      fullPath: '/device-change'
      preLoaderRoute: typeof DeviceChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lgi': {
      id: '/_authenticated/lgi'
      path: '/lgi'
      fullPath: '/lgi'
      preLoaderRoute: typeof AuthenticatedLgiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/firm': {
      id: '/_authenticated/firm'
      path: '/firm'
      fullPath: '/firm'
      preLoaderRoute: typeof AuthenticatedFirmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corps': {
      id: '/_authenticated/corps'
      path: '/corps'
      fullPath: '/corps'
      preLoaderRoute: typeof AuthenticatedCorpsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/media/': {
      id: '/_authenticated/media/'
      path: '/'
      fullPath: '/media/'
      preLoaderRoute: typeof AuthenticatedMediaIndexRouteImport
      parentRoute: typeof AuthenticatedMediaRoute
    }
    '/_authenticated/lgi/': {
      id: '/_authenticated/lgi/'
      path: '/'
      fullPath: '/lgi/'
      preLoaderRoute: typeof AuthenticatedLgiIndexRouteImport
      parentRoute: typeof AuthenticatedLgiRoute
    }
    '/_authenticated/firm/': {
      id: '/_authenticated/firm/'
      path: '/'
      fullPath: '/firm/'
      preLoaderRoute: typeof AuthenticatedFirmIndexRouteImport
      parentRoute: typeof AuthenticatedFirmRoute
    }
    '/_authenticated/corps/': {
      id: '/_authenticated/corps/'
      path: '/'
      fullPath: '/corps/'
      preLoaderRoute: typeof AuthenticatedCorpsIndexRouteImport
      parentRoute: typeof AuthenticatedCorpsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/lgi/attendance': {
      id: '/_authenticated/lgi/attendance'
      path: '/attendance'
      fullPath: '/lgi/attendance'
      preLoaderRoute: typeof AuthenticatedLgiAttendanceRouteImport
      parentRoute: typeof AuthenticatedLgiRoute
    }
    '/_authenticated/lgi/approvals': {
      id: '/_authenticated/lgi/approvals'
      path: '/approvals'
      fullPath: '/lgi/approvals'
      preLoaderRoute: typeof AuthenticatedLgiApprovalsRouteImport
      parentRoute: typeof AuthenticatedLgiRoute
    }
    '/_authenticated/firm/jobs': {
      id: '/_authenticated/firm/jobs'
      path: '/jobs'
      fullPath: '/firm/jobs'
      preLoaderRoute: typeof AuthenticatedFirmJobsRouteImport
      parentRoute: typeof AuthenticatedFirmRoute
    }
    '/_authenticated/corps/scan': {
      id: '/_authenticated/corps/scan'
      path: '/scan'
      fullPath: '/corps/scan'
      preLoaderRoute: typeof AuthenticatedCorpsScanRouteImport
      parentRoute: typeof AuthenticatedCorpsRoute
    }
    '/_authenticated/admin/qr': {
      id: '/_authenticated/admin/qr'
      path: '/qr'
      fullPath: '/admin/qr'
      preLoaderRoute: typeof AuthenticatedAdminQrRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminQrRoute: typeof AuthenticatedAdminQrRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminQrRoute: AuthenticatedAdminQrRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCorpsRouteChildren {
  AuthenticatedCorpsScanRoute: typeof AuthenticatedCorpsScanRoute
  AuthenticatedCorpsIndexRoute: typeof AuthenticatedCorpsIndexRoute
}

const AuthenticatedCorpsRouteChildren: AuthenticatedCorpsRouteChildren = {
  AuthenticatedCorpsScanRoute: AuthenticatedCorpsScanRoute,
  AuthenticatedCorpsIndexRoute: AuthenticatedCorpsIndexRoute,
}

const AuthenticatedCorpsRouteWithChildren =
  AuthenticatedCorpsRoute._addFileChildren(AuthenticatedCorpsRouteChildren)

interface AuthenticatedFirmRouteChildren {
  AuthenticatedFirmJobsRoute: typeof AuthenticatedFirmJobsRoute
  AuthenticatedFirmIndexRoute: typeof AuthenticatedFirmIndexRoute
}

const AuthenticatedFirmRouteChildren: AuthenticatedFirmRouteChildren = {
  AuthenticatedFirmJobsRoute: AuthenticatedFirmJobsRoute,
  AuthenticatedFirmIndexRoute: AuthenticatedFirmIndexRoute,
}

const AuthenticatedFirmRouteWithChildren =
  AuthenticatedFirmRoute._addFileChildren(AuthenticatedFirmRouteChildren)

interface AuthenticatedLgiRouteChildren {
  AuthenticatedLgiApprovalsRoute: typeof AuthenticatedLgiApprovalsRoute
  AuthenticatedLgiAttendanceRoute: typeof AuthenticatedLgiAttendanceRoute
  AuthenticatedLgiIndexRoute: typeof AuthenticatedLgiIndexRoute
}

const AuthenticatedLgiRouteChildren: AuthenticatedLgiRouteChildren = {
  AuthenticatedLgiApprovalsRoute: AuthenticatedLgiApprovalsRoute,
  AuthenticatedLgiAttendanceRoute: AuthenticatedLgiAttendanceRoute,
  AuthenticatedLgiIndexRoute: AuthenticatedLgiIndexRoute,
}

const AuthenticatedLgiRouteWithChildren =
  AuthenticatedLgiRoute._addFileChildren(AuthenticatedLgiRouteChildren)

interface AuthenticatedMediaRouteChildren {
  AuthenticatedMediaIndexRoute: typeof AuthenticatedMediaIndexRoute
}

const AuthenticatedMediaRouteChildren: AuthenticatedMediaRouteChildren = {
  AuthenticatedMediaIndexRoute: AuthenticatedMediaIndexRoute,
}

const AuthenticatedMediaRouteWithChildren =
  AuthenticatedMediaRoute._addFileChildren(AuthenticatedMediaRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCorpsRoute: typeof AuthenticatedCorpsRouteWithChildren
  AuthenticatedFirmRoute: typeof AuthenticatedFirmRouteWithChildren
  AuthenticatedLgiRoute: typeof AuthenticatedLgiRouteWithChildren
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCorpsRoute: AuthenticatedCorpsRouteWithChildren,
  AuthenticatedFirmRoute: AuthenticatedFirmRouteWithChildren,
  AuthenticatedLgiRoute: AuthenticatedLgiRouteWithChildren,
  AuthenticatedMediaRoute: AuthenticatedMediaRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DeviceChangeRoute: DeviceChangeRoute,
  NewsRoute: NewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
